import { Dimensions, StyleSheet } from 'react-native';

export const SCREEN_WIDTH = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#D8D8DB',
  },
  container: {
    padding: 16,
    gap: 12,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#EEF6FF',
    borderWidth: 1,
    borderColor: '#C9DEEF',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  backButtonText: {
    color: '#0B5F8F',
    fontWeight: '800',
    fontSize: 14,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D5E2ED',
    padding: 14,
    gap: 8,
  },
  headerTitle: {
    color: '#0D3D66',
    fontSize: 20,
    fontWeight: '900',
  },
  headerDescription: {
    color: '#0B5F8F',
    fontSize: 13,
    fontWeight: '700',
  },
  headerObjective: {
    color: '#475A6F',
    fontSize: 13,
    lineHeight: 18,
  },
  hintsWrap: {
    gap: 8,
  },
  hintTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
  },
  hintTriggerPressed: {
    opacity: 0.86,
  },
  hintBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0B5F8F',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  hintBubbleText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  hintTriggerText: {
    color: '#0B5F8F',
    fontSize: 13,
    fontWeight: '700',
  },
  hintsCard: {
    backgroundColor: '#FFF9E6',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F2D58A',
    padding: 10,
    gap: 4,
  },
  hintsTitle: {
    color: '#7A5B00',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 2,
  },
  hintItem: {
    color: '#5D4800',
    fontSize: 12,
    lineHeight: 17,
  },
  missionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D5E2ED',
    padding: 14,
    gap: 10,
  },
  sectionTitle: {
    color: '#0D3D66',
    fontSize: 16,
    fontWeight: '800',
  },
  sectionSubtitle: {
    color: '#607287',
    fontSize: 13,
  },
  caseContext: {
    color: '#4A6078',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  polygonBoard: {
    width: '100%',
    maxWidth: 340,
    alignSelf: 'center',
    height: 210,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#D3E3F1',
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  polygonEdge: {
    position: 'absolute',
    height: 4,
    borderRadius: 999,
    backgroundColor: '#9CC3DE',
  },
  polygonEdgeTouched: {
    backgroundColor: '#0B5F8F',
  },
  polygonTouchPoint: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#9CC3DE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  polygonTouchPointTouched: {
    backgroundColor: '#0B5F8F',
    borderColor: '#0B5F8F',
  },
  polygonTouchPointText: {
    color: '#355877',
    fontSize: 12,
    fontWeight: '800',
  },
  polygonTouchPointTextTouched: {
    color: '#FFFFFF',
  },
  trainingCard: {
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#D3E3F1',
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  trainingTitle: {
    color: '#0D3D66',
    fontSize: 14,
    fontWeight: '800',
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 14,
    color: '#0D3D66',
  },
  equationAdjustGrid: {
    gap: 8,
  },
  equationAdjustCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  equationAdjustLabel: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '800',
  },
  equationAdjustControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  equationAdjustValue: {
    color: '#0D3D66',
    fontSize: 20,
    fontWeight: '900',
    minWidth: 34,
    textAlign: 'center',
  },
  equationStatusWrap: {
    gap: 6,
    marginTop: 2,
  },
  equationStatusText: {
    color: '#4A6078',
    fontSize: 12,
    fontWeight: '700',
  },
  equationStatusTextOk: {
    color: '#166534',
  },
  areaPreviewWrap: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  areaShapeCard: {
    width: 144,
    minHeight: 132,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D5E2ED',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    gap: 8,
  },
  areaPreviewInfo: {
    flex: 1,
    gap: 4,
  },
  areaFormulaLabel: {
    color: '#0B5F8F',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  areaFormulaValue: {
    color: '#1F3E66',
    fontSize: 16,
    fontWeight: '900',
  },
  areaHint: {
    color: '#4A6078',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  squareShape: {
    width: 68,
    height: 68,
    borderWidth: 3,
    borderColor: '#0B5F8F',
    backgroundColor: '#EAF4FC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rectangleShape: {
    width: 88,
    height: 56,
    borderWidth: 3,
    borderColor: '#0B5F8F',
    backgroundColor: '#EAF4FC',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  triangleShape: {
    width: 0,
    height: 0,
    borderLeftWidth: 36,
    borderRightWidth: 36,
    borderBottomWidth: 62,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#0B5F8F',
    marginTop: 4,
  },
  triangleLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 92,
    marginTop: -2,
  },
  shapeCaption: {
    color: '#0D3D66',
    fontSize: 12,
    fontWeight: '800',
  },
  shapeMeasureText: {
    color: '#0D3D66',
    fontSize: 13,
    fontWeight: '900',
  },
  shapeMeasureTextSmall: {
    color: '#0D3D66',
    fontSize: 11,
    fontWeight: '800',
  },
  trainingBoard: {
    height: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D5E2ED',
    backgroundColor: '#FFFFFF',
    position: 'relative',
    overflow: 'hidden',
  },
  trainingLine: {
    position: 'absolute',
    height: 3,
    backgroundColor: '#9CC3DE',
    borderRadius: 999,
  },
  vertexDot: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderRadius: 17,
    marginLeft: -17,
    marginTop: -17,
    backgroundColor: '#0B5F8F',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vertexDotTouched: {
    backgroundColor: '#16A34A',
  },
  vertexDotText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  trainingMeta: {
    color: '#4A6078',
    fontSize: 12,
    fontWeight: '700',
  },
  optionList: {
    gap: 8,
  },
  quizOption: {
    borderWidth: 1,
    borderColor: '#C8D8E8',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
  },
  quizOptionPressed: {
    opacity: 0.85,
  },
  quizOptionActive: {
    borderColor: '#0B5F8F',
    backgroundColor: '#EEF6FF',
  },
  quizOptionText: {
    color: '#1F3E66',
    fontSize: 14,
    fontWeight: '700',
  },
  quizOptionTextActive: {
    color: '#0B5F8F',
  },
  quizFeedback: {
    fontSize: 13,
    fontWeight: '700',
  },
  quizFeedbackOk: {
    color: '#166534',
  },
  quizFeedbackWrong: {
    color: '#B91C1C',
  },
  nextStepButton: {
    borderRadius: 10,
    backgroundColor: '#0B5F8F',
    paddingVertical: 10,
    alignItems: 'center',
  },
  nextStepButtonPressed: {
    opacity: 0.86,
  },
  nextStepButtonDisabled: {
    opacity: 0.45,
  },
  nextStepButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  sceneMock: {
    borderRadius: 14,
    backgroundColor: '#EEF4FA',
    borderWidth: 1,
    borderColor: '#CAD9E8',
    overflow: 'hidden',
  },
  sceneLabel: {
    color: '#355877',
    fontSize: 12,
    fontWeight: '700',
    padding: 10,
  },
  photoRow: {
    paddingHorizontal: 10,
    paddingBottom: 10,
    gap: 8,
  },
  photoCard: {
    width: '100%',
    aspectRatio: 1308 / 1024,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#CAD9E8',
  },
  photoCardFill: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  photoCardImage: {
    borderRadius: 10,
    resizeMode: 'cover',
  },
  photoOverlay: {
    backgroundColor: 'rgba(11, 95, 143, 0.72)',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  photoTitle: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  hotspot: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0B5F8F',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -16,
    marginTop: -16,
  },
  hotspotCaptured: {
    backgroundColor: '#16A34A',
  },
  hotspotText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  progressPanel: {
    gap: 6,
  },
  sceneHint: {
    color: '#4A6078',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '600',
  },
  progressText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  progressBarBase: {
    height: 8,
    borderRadius: 5,
    backgroundColor: '#E1E7EF',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0B5F8F',
  },
  dragArea: {
    height: 390,
    borderRadius: 12,
    backgroundColor: '#F6FAFD',
    borderWidth: 1,
    borderColor: '#DBE5F0',
    position: 'relative',
    overflow: 'hidden',
  },
  dropZone: {
    position: 'absolute',
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropZoneGreen: {
    borderColor: '#22C55E',
    backgroundColor: '#ECFDF3',
  },
  dropZoneRed: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  dropZoneTitle: {
    color: '#334155',
    fontWeight: '800',
    fontSize: 12,
  },
  dragChip: {
    position: 'absolute',
    minWidth: 150,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C9D8E6',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dragChipSelected: {
    borderColor: '#0B5F8F',
    borderWidth: 2,
    backgroundColor: '#EAF4FC',
  },
  dragChipText: {
    color: '#0D3D66',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  tapAssistText: {
    color: '#4A6078',
    fontSize: 12,
    fontWeight: '600',
    marginTop: -2,
    marginBottom: 2,
  },
  answerList: {
    gap: 5,
  },
  answerItem: {
    color: '#475A6F',
    fontSize: 12,
  },
  answerItemOk: {
    color: '#166534',
    fontWeight: '700',
  },
  answerItemWrong: {
    color: '#B91C1C',
    fontWeight: '700',
  },
  sidesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sideChip: {
    backgroundColor: '#EDF4FB',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sideChipTouched: {
    backgroundColor: '#0B5F8F',
    borderColor: '#0B5F8F',
  },
  sideChipText: {
    color: '#355877',
    fontSize: 12,
    fontWeight: '700',
  },
  sideChipTextTouched: {
    color: '#FFFFFF',
  },
  counterText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  reportList: {
    gap: 10,
  },
  reportHelpCard: {
    backgroundColor: '#EEF6FF',
    borderWidth: 1,
    borderColor: '#C9DEEF',
    borderRadius: 12,
    padding: 10,
    gap: 4,
  },
  reportHelpTitle: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '900',
  },
  reportHelpText: {
    color: '#355877',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  reportProgressCard: {
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  reportProgressText: {
    color: '#0D3D66',
    fontSize: 12,
    fontWeight: '800',
  },
  reportProgressBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E1E7EF',
    overflow: 'hidden',
  },
  reportProgressBarFill: {
    height: '100%',
    backgroundColor: '#16A34A',
  },
  reportProgressCaption: {
    color: '#4A6078',
    fontSize: 11,
    fontWeight: '700',
    marginTop: -2,
  },
  reportCard: {
    backgroundColor: '#F8FBFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D3E1EE',
    padding: 10,
    gap: 8,
  },
  reportCardExpanded: {
    borderColor: '#AFCFE8',
    backgroundColor: '#FDFEFF',
  },
  reportCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  reportCardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reportStatusPill: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FDBA74',
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  reportStatusPillDone: {
    backgroundColor: '#ECFDF3',
    borderColor: '#22C55E',
  },
  reportStatusText: {
    color: '#9A3412',
    fontSize: 10,
    fontWeight: '900',
  },
  reportStatusTextDone: {
    color: '#166534',
  },
  reportChevron: {
    color: '#0B5F8F',
    fontSize: 18,
    fontWeight: '900',
    width: 16,
    textAlign: 'center',
  },
  reportCardTitle: {
    color: '#0D3D66',
    fontSize: 13,
    fontWeight: '800',
  },
  reportSubmittedText: {
    color: '#4A6078',
    fontSize: 12,
    fontWeight: '600',
  },
  reportSubmittedChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  reportSubmittedChip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  reportSubmittedChipText: {
    color: '#355877',
    fontSize: 11,
    fontWeight: '700',
  },
  reportVisualRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D3E1EE',
    borderRadius: 10,
    padding: 8,
  },
  reportShapePreviewBox: {
    width: 96,
    height: 78,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DBE5F0',
    backgroundColor: '#F8FBFF',
    position: 'relative',
    overflow: 'hidden',
  },
  reportShapeEdge: {
    position: 'absolute',
    height: 3,
    borderRadius: 999,
    backgroundColor: '#0B5F8F',
  },
  reportVisualTextWrap: {
    flex: 1,
    gap: 2,
  },
  reportVisualTitle: {
    color: '#0B5F8F',
    fontSize: 11,
    fontWeight: '900',
  },
  reportVisualText: {
    color: '#4A6078',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  reportPromptText: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '800',
  },
  reportDecisionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  reportDecisionButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D7E6',
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  reportDecisionButtonActive: {
    borderColor: '#0B5F8F',
    borderWidth: 2,
    backgroundColor: '#EEF6FF',
  },
  reportDecisionButtonPressed: {
    opacity: 0.86,
  },
  reportDecisionButtonText: {
    color: '#1F3E66',
    fontSize: 12,
    fontWeight: '800',
  },
  reportDecisionButtonTextActive: {
    color: '#0B5F8F',
  },
  reportCorrectionWrap: {
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#D7E4EF',
    paddingTop: 8,
  },
  reportCorrectionLabel: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '800',
  },
  reportCorrectionHint: {
    color: '#355877',
    fontSize: 11,
    fontWeight: '700',
  },
  optionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C7D7E6',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  optionButtonPressed: {
    opacity: 0.86,
  },
  optionButtonDisabled: {
    opacity: 0.55,
  },
  optionButtonSelected: {
    borderColor: '#0B5F8F',
    borderWidth: 2,
  },
  optionButtonText: {
    color: '#1F3E66',
    fontSize: 12,
    fontWeight: '700',
  },
  tapList: {
    gap: 10,
  },
  tapRow: {
    backgroundColor: '#F8FBFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D3E1EE',
    padding: 12,
    gap: 10,
  },
  tapRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tapRowTitle: {
    color: '#0D3D66',
    fontWeight: '800',
    fontSize: 13,
    flex: 1,
    paddingRight: 10,
  },
  tapRowStatusOk: {
    color: '#166534',
    fontWeight: '900',
    fontSize: 14,
  },
  tapRowStatusWrong: {
    color: '#B91C1C',
    fontWeight: '900',
    fontSize: 14,
  },
  tapRowStatusPending: {
    color: '#94A3B8',
    fontWeight: '900',
    fontSize: 14,
  },
  tapButtonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  tapButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C9DEEF',
    borderRadius: 999,
    paddingVertical: 8,
    alignItems: 'center',
  },
  tapButtonActive: {
    backgroundColor: '#0B5F8F',
    borderColor: '#0B5F8F',
  },
  tapButtonPressed: {
    opacity: 0.85,
  },
  tapButtonText: {
    color: '#0B5F8F',
    fontWeight: '900',
    fontSize: 12,
  },
  tapButtonTextActive: {
    color: '#FFFFFF',
  },
  finalBossSectionTitle: {
    color: '#0B5F8F',
    fontWeight: '900',
    fontSize: 12,
    marginTop: 2,
  },
  convexityRow: {
    flexDirection: 'row',
    gap: 10,
  },
  convexityButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#C9DEEF',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  convexityButtonSelected: {
    borderColor: '#0B5F8F',
    borderWidth: 2,
  },
  convexityButtonDisabled: {
    opacity: 0.5,
  },
  convexityButtonPressed: {
    opacity: 0.85,
  },
  convexityButtonText: {
    color: '#0D3D66',
    fontWeight: '900',
    fontSize: 12,
  },
  checkButton: {
    backgroundColor: '#0B5F8F',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 2,
  },
  checkButtonDisabled: {
    opacity: 0.5,
  },
  checkButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  checkButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 13,
  },
  nextReportButton: {
    backgroundColor: '#EEF6FF',
    borderWidth: 1,
    borderColor: '#C9DEEF',
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  nextReportButtonPressed: {
    opacity: 0.85,
  },
  nextReportButtonText: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '800',
  },
  feedbackText: {
    color: '#0B5F8F',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  feedbackHint: {
    color: '#4A6078',
    fontSize: 12,
    fontWeight: '600',
  },
  nextCaseButton: {
    backgroundColor: '#0B5F8F',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  nextCaseButtonPressed: {
    opacity: 0.86,
  },
  nextCaseButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  tipText: {
    color: '#475A6F',
    fontSize: 13,
    lineHeight: 18,
  },
  successCard: {
    backgroundColor: '#EAF9EE',
    borderWidth: 1,
    borderColor: '#A8E0BA',
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  successTitle: {
    color: '#166534',
    fontSize: 15,
    fontWeight: '900',
  },
  successText: {
    color: '#166534',
    fontSize: 13,
    lineHeight: 18,
  },
  completeButton: {
    backgroundColor: '#0B5F8F',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
  },
  completeButtonPressed: {
    opacity: 0.86,
  },
  completeButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 14,
  },
  afterCompleteWrap: {
    gap: 8,
  },
  nextMissionButton: {
    backgroundColor: '#16A34A',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
  },
  nextMissionButtonPressed: {
    opacity: 0.86,
  },
  nextMissionButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 14,
  },
  alreadyDoneBadge: {
    borderRadius: 10,
    backgroundColor: '#E8F6EC',
    borderWidth: 1,
    borderColor: '#BFE7CC',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  alreadyDoneText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  completionFeedback: {
    color: '#0B5F8F',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  ahaCard: {
    backgroundColor: '#FFF4D6',
    borderWidth: 1,
    borderColor: '#F2D58A',
    borderRadius: 16,
    padding: 12,
    gap: 4,
  },
  ahaTitle: {
    color: '#7A5B00',
    fontSize: 14,
    fontWeight: '900',
  },
  ahaText: {
    color: '#5D4800',
    fontSize: 13,
    lineHeight: 18,
  },
  notFound: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  notFoundText: {
    color: '#1F3E66',
    fontSize: 16,
    fontWeight: '800',
  },
});
